language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27,pep8
        - os: linux
          python: 3.5
          env: TOXENV=py35,pep8

dist: trusty
sudo: required

notifications:
    email: false

before_install:
    - pip install tox
    - pip install python-coveralls

script:
    - tox

after_success:
  - coveralls
